import { Data as Data_ } from './Data';
import { AboutMe as AboutMe_ } from './AboutMe';
import { Bio as Bio_ } from './Bio';
import { Experience as Experience_ } from './Experience';
import { Paragraph as Paragraph_, SpanItem as SpanItem_ } from './Global';
import { Project as Project_, ProjectLink as ProjectLink_ } from './Project';
import { Skill as Skill_ } from './Skill';
import { SkillLevel as SkillLevel_ } from './SkillLevel';
import { SocialIcon as SocialIcon_ } from './SocialIcon';
import { Certificate as Certificate_ } from './Certificate';
import { Appearance as Appearance_, AppearanceLink as AppearanceLink_ } from './Appearance';

export type Data = Data_;
export type AboutMe = AboutMe_;
export type Bio = Bio_;
export type Experience = Experience_;
export type Paragraph = Paragraph_;
export type SpanItem = SpanItem_;
export type Project = Project_;
export type ProjectLink = ProjectLink_;
export type Skill = Skill_;
export type SkillLevel = SkillLevel_;
export type SocialIcon = SocialIcon_;
export type Certificate = Certificate_;
export type Appearance = Appearance_;
export type AppearanceLink = AppearanceLink_;